/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Jesus
 */
public class OperacionInOut extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public String id;
    public String operacion;
    public OperacionInOut() {
        initComponents();
    }
    public OperacionInOut(String id,String operacion)
    {
        this.id = id;
        this.operacion= operacion;
        initComponents();
        lblNum.setText(id);
        lblOpName.setText(operacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        btnBackInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblOpName = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblOpName1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(112, 136, 113));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BankIt");
        jLabel1.setAlignmentY(0.0F);

        lblNum.setBackground(new java.awt.Color(255, 255, 255));
        lblNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        lblNum.setText("0000000000");
        lblNum.setAlignmentY(0.0F);

        btnBackInicio.setBackground(new java.awt.Color(112, 136, 113));
        btnBackInicio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnBackInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnBackInicio.setText("Atras");
        btnBackInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackInicio))
                .addGap(20, 20, 20))
        );

        jPanel1.setBackground(new java.awt.Color(254, 243, 226));
        jPanel1.setFocusTraversalPolicyProvider(true);

        lblOpName.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblOpName.setForeground(new java.awt.Color(0, 102, 118));
        lblOpName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOpName.setText("Nombre operacion");

        btnContinuar.setBackground(new java.awt.Color(112, 136, 113));
        btnContinuar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Ingresar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblOpName1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblOpName1.setForeground(new java.awt.Color(0, 102, 118));
        lblOpName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOpName1.setText("Cantidad:");

        txtCantidad.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblOpName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblOpName)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblOpName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpName1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackInicioActionPerformed
        // TODO add your handling code here:
        Menu menu =new Menu(this.id);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackInicioActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String tipo=" ";
        switch (this.operacion) {
            case "Sacar dinero debito":
                // se hara el procedimiento para sacar dinero a deb
               // por el momento hasta que no se conecten las cosas ira directamente al recibo
                tipo ="debito";
                Recibo reciboDeb =new Recibo(this.id,this.operacion,tipo);
                reciboDeb.setVisible(true);
                reciboDeb.setLocationRelativeTo(null);
                this.setVisible(false);
                break;
            case "Consignar dinero":
                // se preguntara a donde consignar dinero si a cred o a deb y luego si se consignara
                ConsignarEn consEn = new ConsignarEn(this.id,"Consignar dinero");
                consEn.setVisible(true);
                consEn.setLocationRelativeTo(null);
                this.setVisible(false);
                break;
            case "Hacer avance":
                // se hara el procedimiento para sacar dinero a cred
                 // por el momento hasta que no se conecten las cosas ira directamente al recibo
                tipo ="credito";
                Recibo reciboCred =new Recibo(this.id,this.operacion,tipo);
                reciboCred.setVisible(true);
                reciboCred.setLocationRelativeTo(null);
                this.setVisible(false);
                break;
            default:
                // en caso de que pase algo raro
                OperacionInvalida opInvalida =new OperacionInvalida(this.id,"Operación invalida");
                opInvalida.setVisible(true);
                opInvalida.setLocationRelativeTo(null);
                this.setVisible(false);
                break;
 }
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackInicio;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblOpName;
    private javax.swing.JLabel lblOpName1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
